"use client";
import { useState, useEffect } from 'react';
import { X, Upload, Loader2, Play, CheckCircle, Lock, Globe, EyeOff, AlertCircle, Check, Clock, XCircle } from 'lucide-react';
import clsx from 'clsx';

interface SNSUploadModalProps {
    project: {
        id: string;
        title: string;
        videoPath: string;
        description?: string;
    };
    onClose: () => void;
    onUploadSuccess: (url: string) => void;
}

type UploadStatus = 'idle' | 'uploading' | 'success' | 'error';

interface PlatformUploadState {
    selected: boolean;
    connected: boolean;
    status: UploadStatus;
    accountName?: string;
    resultUrl?: string;
    error?: string;
}

interface PlatformDef {
    id: string;
    name: string;
    icon: string;
    colorClass: string;
    activeClass: string;
    statusUrl: string;
    uploadUrl: string;
    loginUrl: string;
}

const PLATFORMS: PlatformDef[] = [
    {
        id: 'youtube',
        name: 'YouTube',
        icon: '▶',
        colorClass: 'border-red-600/50 bg-red-600/10',
        activeClass: 'ring-red-500',
        statusUrl: '/api/auth/youtube/status',
        uploadUrl: '/api/upload/youtube',
        loginUrl: '/api/auth/youtube/login'
    },
    {
        id: 'instagram',
        name: 'Instagram',
        icon: '📷',
        colorClass: 'border-pink-500/50 bg-pink-500/10',
        activeClass: 'ring-pink-500',
        statusUrl: '/api/auth/instagram/status',
        uploadUrl: '/api/upload/instagram',
        loginUrl: '/api/auth/instagram/login'
    },
    {
        id: 'tiktok',
        name: 'TikTok',
        icon: '♪',
        colorClass: 'border-cyan-400/50 bg-cyan-400/10',
        activeClass: 'ring-cyan-400',
        statusUrl: '/api/auth/tiktok/status',
        uploadUrl: '/api/upload/tiktok',
        loginUrl: '/api/auth/tiktok/login'
    }
];

export default function SNSUploadModal({ project, onClose, onUploadSuccess }: SNSUploadModalProps) {
    const [deploying, setDeploying] = useState(false);
    const [title, setTitle] = useState(project.title);
    const [description, setDescription] = useState(project.description || `Generated by AI Video Editor`);
    const [tags, setTags] = useState("AI, Video, Generated");
    const [privacy, setPrivacy] = useState<'private' | 'unlisted' | 'public'>('private');

    const [platformStates, setPlatformStates] = useState<Record<string, PlatformUploadState>>({});
    const [loadingStatuses, setLoadingStatuses] = useState(true);

    // Fetch connection statuses for all platforms
    useEffect(() => {
        const checkAll = async () => {
            setLoadingStatuses(true);
            const newStates: Record<string, PlatformUploadState> = {};

            await Promise.all(PLATFORMS.map(async (p) => {
                try {
                    const res = await fetch(p.statusUrl);
                    const data = await res.json();
                    newStates[p.id] = {
                        selected: false,
                        connected: data.connected || false,
                        status: 'idle',
                        accountName: data.channelName || data.username || data.displayName
                    };
                } catch {
                    newStates[p.id] = { selected: false, connected: false, status: 'idle' };
                }
            }));

            setPlatformStates(newStates);
            setLoadingStatuses(false);
        };
        checkAll();
    }, []);

    const togglePlatform = (id: string) => {
        if (deploying) return;
        setPlatformStates(prev => ({
            ...prev,
            [id]: { ...prev[id], selected: !prev[id]?.selected }
        }));
    };

    const selectedCount = Object.values(platformStates).filter(s => s.selected && s.connected).length;

    // Batch deploy
    const handleDeploy = async () => {
        const targets = PLATFORMS.filter(p => platformStates[p.id]?.selected && platformStates[p.id]?.connected);
        if (targets.length === 0) return;

        setDeploying(true);

        for (const platform of targets) {
            // Mark uploading
            setPlatformStates(prev => ({
                ...prev,
                [platform.id]: { ...prev[platform.id], status: 'uploading' }
            }));

            try {
                // Build platform-specific payload
                let body: any = { videoPath: project.videoPath };

                if (platform.id === 'youtube') {
                    body = {
                        ...body,
                        title,
                        description,
                        tags: tags.split(',').map(t => t.trim()),
                        privacyStatus: privacy
                    };
                } else if (platform.id === 'instagram') {
                    body = {
                        ...body,
                        caption: `${title}\n\n${description}\n\n${tags.split(',').map(t => '#' + t.trim().replace(/\s+/g, '')).join(' ')}`
                    };
                } else if (platform.id === 'tiktok') {
                    body = {
                        ...body,
                        title,
                        description: `${description}\n${tags.split(',').map(t => '#' + t.trim().replace(/\s+/g, '')).join(' ')}`,
                        privacyLevel: privacy === 'public' ? 'PUBLIC_TO_EVERYONE' :
                            privacy === 'unlisted' ? 'MUTUAL_FOLLOW_FRIENDS' : 'SELF_ONLY'
                    };
                }

                const res = await fetch(platform.uploadUrl, {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify(body)
                });
                const data = await res.json();

                if (data.success || data.url) {
                    // Log upload
                    await fetch('/api/projects/log-upload', {
                        method: 'POST',
                        headers: { 'Content-Type': 'application/json' },
                        body: JSON.stringify({
                            projectId: project.id,
                            uploadRecord: {
                                platform: platform.id,
                                videoId: data.videoId || data.mediaId || data.publishId || '',
                                url: data.url || '',
                                status: privacy
                            }
                        })
                    }).catch(err => console.error("Failed to log upload:", err));

                    setPlatformStates(prev => ({
                        ...prev,
                        [platform.id]: {
                            ...prev[platform.id],
                            status: 'success',
                            resultUrl: data.url
                        }
                    }));
                } else {
                    throw new Error(data.error || "Upload failed");
                }
            } catch (e: any) {
                setPlatformStates(prev => ({
                    ...prev,
                    [platform.id]: {
                        ...prev[platform.id],
                        status: 'error',
                        error: e.message || 'Unknown error'
                    }
                }));
            }
        }

        setDeploying(false);

        // If any succeeded, trigger success callback with first URL
        const firstSuccess = targets.find(t => platformStates[t.id]?.status === 'success');
        if (firstSuccess) {
            // Delay slightly so state updates propagate
            setTimeout(() => {
                const state = platformStates[firstSuccess.id];
                if (state?.resultUrl) onUploadSuccess(state.resultUrl);
            }, 500);
        }
    };

    const allDone = deploying === false && Object.values(platformStates).some(s => s.status === 'success' || s.status === 'error');

    return (
        <div className="fixed inset-0 z-[400] bg-black/80 backdrop-blur-sm flex items-center justify-center p-4 animate-in fade-in zoom-in-95 duration-200">
            <div className="bg-[#1a1a1a] w-full max-w-2xl rounded-2xl border border-white/10 shadow-2xl flex flex-col max-h-[90vh] overflow-hidden">

                {/* Header */}
                <div className="p-4 border-b border-white/10 flex justify-between items-center bg-black/20">
                    <h3 className="font-bold text-lg text-white flex items-center gap-2">
                        🚀 Multi-Platform Deploy
                    </h3>
                    <button onClick={onClose} disabled={deploying} className="p-1 hover:bg-white/10 rounded-full text-gray-400 hover:text-white">
                        <X className="w-5 h-5" />
                    </button>
                </div>

                <div className="flex-1 overflow-y-auto p-6 space-y-6">

                    {/* Platform Selector */}
                    <div>
                        <label className="block text-xs font-bold text-gray-500 uppercase mb-3">Select Platforms</label>
                        <div className="grid grid-cols-3 gap-3">
                            {loadingStatuses ? (
                                <div className="col-span-3 flex justify-center py-6">
                                    <Loader2 className="w-6 h-6 animate-spin text-gray-500" />
                                </div>
                            ) : PLATFORMS.map(p => {
                                const state = platformStates[p.id];
                                const connected = state?.connected;
                                const selected = state?.selected;
                                const uploadStatus = state?.status || 'idle';

                                return (
                                    <button
                                        key={p.id}
                                        onClick={() => connected && togglePlatform(p.id)}
                                        disabled={!connected || deploying}
                                        className={clsx(
                                            "relative p-4 rounded-xl border-2 flex flex-col items-center gap-2 transition-all",
                                            !connected ? "opacity-40 cursor-not-allowed border-white/5 bg-black/30" :
                                                selected ? `${p.colorClass} ring-2 ${p.activeClass}` :
                                                    "border-white/10 bg-black/20 hover:border-white/20"
                                        )}
                                    >
                                        {/* Status badge */}
                                        {uploadStatus === 'success' && (
                                            <div className="absolute -top-2 -right-2 w-6 h-6 rounded-full bg-green-500 flex items-center justify-center shadow-lg">
                                                <Check className="w-3 h-3 text-white" />
                                            </div>
                                        )}
                                        {uploadStatus === 'uploading' && (
                                            <div className="absolute -top-2 -right-2 w-6 h-6 rounded-full bg-blue-500 flex items-center justify-center shadow-lg">
                                                <Loader2 className="w-3 h-3 text-white animate-spin" />
                                            </div>
                                        )}
                                        {uploadStatus === 'error' && (
                                            <div className="absolute -top-2 -right-2 w-6 h-6 rounded-full bg-red-500 flex items-center justify-center shadow-lg">
                                                <XCircle className="w-3 h-3 text-white" />
                                            </div>
                                        )}

                                        <div className={clsx("w-10 h-10 rounded-full flex items-center justify-center text-white text-sm",
                                            p.id === 'youtube' ? 'bg-red-600' :
                                                p.id === 'instagram' ? 'bg-gradient-to-br from-pink-500 to-purple-600' :
                                                    'bg-black border border-white/20'
                                        )}>
                                            {p.icon}
                                        </div>
                                        <span className="font-bold text-sm">{p.name}</span>

                                        {connected ? (
                                            <span className="text-[10px] text-green-400 flex items-center gap-1">
                                                <CheckCircle className="w-3 h-3" />
                                                {state?.accountName ? state.accountName.substring(0, 15) : 'Connected'}
                                            </span>
                                        ) : (
                                            <span
                                                onClick={(e) => {
                                                    e.stopPropagation();
                                                    window.open(p.loginUrl, `${p.name} Connect`, 'width=600,height=700');
                                                }}
                                                className="text-[10px] text-amber-400 underline hover:text-amber-300 cursor-pointer"
                                            >
                                                Connect →
                                            </span>
                                        )}

                                        {/* Checkbox */}
                                        {connected && (
                                            <div className={clsx(
                                                "absolute top-2 left-2 w-5 h-5 rounded border-2 flex items-center justify-center transition-all",
                                                selected ? "bg-white border-white" : "border-white/30"
                                            )}>
                                                {selected && <Check className="w-3 h-3 text-black" />}
                                            </div>
                                        )}
                                    </button>
                                );
                            })}
                        </div>
                    </div>

                    {/* Metadata Inputs */}
                    <div className="space-y-4">
                        <div>
                            <label className="block text-xs font-bold text-gray-500 uppercase mb-1">Video Title</label>
                            <input
                                value={title}
                                onChange={e => setTitle(e.target.value)}
                                disabled={deploying}
                                className="w-full bg-black/30 border border-white/10 rounded-lg p-3 text-white focus:border-purple-500 outline-none disabled:opacity-50"
                            />
                        </div>

                        <div>
                            <label className="block text-xs font-bold text-gray-500 uppercase mb-1">Description</label>
                            <textarea
                                value={description}
                                onChange={e => setDescription(e.target.value)}
                                rows={4}
                                disabled={deploying}
                                className="w-full bg-black/30 border border-white/10 rounded-lg p-3 text-white focus:border-purple-500 outline-none resize-none disabled:opacity-50"
                            />
                        </div>

                        <div>
                            <label className="block text-xs font-bold text-gray-500 uppercase mb-1">Tags (comma separated)</label>
                            <input
                                value={tags}
                                onChange={e => setTags(e.target.value)}
                                placeholder="AI, Vlog, Tech..."
                                disabled={deploying}
                                className="w-full bg-black/30 border border-white/10 rounded-lg p-3 text-white focus:border-purple-500 outline-none disabled:opacity-50"
                            />
                            <p className="text-[10px] text-gray-500 mt-1">Instagram & TikTok: auto-converted to #hashtags</p>
                        </div>

                        <div>
                            <label className="block text-xs font-bold text-gray-500 uppercase mb-2">Privacy</label>
                            <div className="flex bg-black/30 p-1 rounded-lg border border-white/10">
                                {(['private', 'unlisted', 'public'] as const).map(p => (
                                    <button
                                        key={p}
                                        onClick={() => !deploying && setPrivacy(p)}
                                        disabled={deploying}
                                        className={clsx(
                                            "flex-1 py-2 rounded-md text-xs font-bold flex items-center justify-center gap-2 transition-all",
                                            privacy === p ? "bg-white/10 text-white shadow" : "text-gray-500 hover:text-gray-300"
                                        )}
                                    >
                                        {p === 'private' && <Lock className="w-3 h-3" />}
                                        {p === 'unlisted' && <EyeOff className="w-3 h-3" />}
                                        {p === 'public' && <Globe className="w-3 h-3" />}
                                        {p.charAt(0).toUpperCase() + p.slice(1)}
                                    </button>
                                ))}
                            </div>
                        </div>
                    </div>

                    {/* Deploy Results */}
                    {allDone && (
                        <div className="space-y-2">
                            <label className="block text-xs font-bold text-gray-500 uppercase">Deploy Results</label>
                            {PLATFORMS.filter(p => platformStates[p.id]?.status === 'success' || platformStates[p.id]?.status === 'error').map(p => {
                                const state = platformStates[p.id];
                                return (
                                    <div key={p.id} className={clsx(
                                        "flex items-center justify-between p-3 rounded-lg text-sm",
                                        state?.status === 'success' ? "bg-green-500/10 text-green-300" : "bg-red-500/10 text-red-300"
                                    )}>
                                        <div className="flex items-center gap-2">
                                            {state?.status === 'success' ? <CheckCircle className="w-4 h-4" /> : <XCircle className="w-4 h-4" />}
                                            <span className="font-bold">{p.name}</span>
                                        </div>
                                        {state?.status === 'success' && state.resultUrl ? (
                                            <a href={state.resultUrl} target="_blank" rel="noopener noreferrer" className="text-xs underline hover:text-white">
                                                View →
                                            </a>
                                        ) : (
                                            <span className="text-xs">{state?.error || 'Failed'}</span>
                                        )}
                                    </div>
                                );
                            })}
                        </div>
                    )}
                </div>

                {/* Footer */}
                <div className="p-4 border-t border-white/10 bg-black/20 flex justify-between items-center">
                    <div className="text-xs text-gray-500">
                        {selectedCount > 0 && !deploying && `${selectedCount} platform${selectedCount > 1 ? 's' : ''} selected`}
                        {deploying && (
                            <span className="flex items-center gap-2 text-blue-400">
                                <Loader2 className="w-3 h-3 animate-spin" /> Deploying...
                            </span>
                        )}
                    </div>
                    <div className="flex gap-3">
                        <button
                            onClick={onClose}
                            disabled={deploying}
                            className="px-4 py-2 rounded-lg text-sm font-bold text-gray-400 hover:text-white hover:bg-white/5 transition-colors"
                        >
                            {allDone ? 'Close' : 'Cancel'}
                        </button>
                        {!allDone && (
                            <button
                                onClick={handleDeploy}
                                disabled={deploying || selectedCount === 0}
                                className={clsx(
                                    "px-6 py-2 rounded-lg text-sm font-bold shadow-lg transition-all flex items-center gap-2",
                                    selectedCount > 0 && !deploying
                                        ? "bg-gradient-to-r from-purple-600 to-pink-600 hover:from-purple-500 hover:to-pink-500 text-white shadow-purple-900/30"
                                        : "bg-gray-700 text-gray-500 cursor-not-allowed"
                                )}
                            >
                                {deploying ? <Loader2 className="w-4 h-4 animate-spin" /> : <Upload className="w-4 h-4" />}
                                {deploying ? 'Deploying...' : `Deploy to ${selectedCount} Platform${selectedCount !== 1 ? 's' : ''}`}
                            </button>
                        )}
                    </div>
                </div>

            </div>
        </div>
    );
}
