"use client";
import { useState, useEffect } from 'react';
import { X, Upload, Loader2, Play, CheckCircle, Lock, Globe, EyeOff } from 'lucide-react';
import clsx from 'clsx';

interface SNSUploadModalProps {
    project: {
        id: string;
        title: string;
        videoPath: string;
        description?: string; // If available
    };
    onClose: () => void;
    onUploadSuccess: (url: string) => void;
}

export default function SNSUploadModal({ project, onClose, onUploadSuccess }: SNSUploadModalProps) {
    const [loading, setLoading] = useState(false);
    const [platform, setPlatform] = useState<'youtube'>('youtube');
    const [privacy, setPrivacy] = useState<'private' | 'unlisted' | 'public'>('private');
    const [title, setTitle] = useState(project.title);
    const [description, setDescription] = useState(project.description || `Generated by AI Video Editor`);
    const [tags, setTags] = useState("AI, Video, Generated");

    const [status, setStatus] = useState<{ connected: boolean, channelName?: string } | null>(null);

    useEffect(() => {
        // Fetch connection status
        fetch('/api/auth/youtube/status')
            .then(res => res.json())
            .then(data => setStatus(data))
            .catch(err => console.error("Status check failed", err));
    }, []);

    const handleUpload = async () => {
        if (!status?.connected) {
            alert("Please connect your YouTube account in Settings first.");
            return;
        }

        setLoading(true);
        try {
            const res = await fetch('/api/upload/youtube', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    videoPath: project.videoPath,
                    title,
                    description,
                    tags: tags.split(',').map(t => t.trim()),
                    privacyStatus: privacy
                })
            });
            const data = await res.json();
            if (data.url) {
                // Extract Video ID reliably
                let videoId = 'unknown';
                if (data.videoId) {
                    videoId = data.videoId;
                } else if (data.url.includes('v=')) {
                    videoId = data.url.split('v=')[1].split('&')[0];
                } else if (data.url.includes('youtu.be/')) {
                    videoId = data.url.split('youtu.be/')[1].split('?')[0];
                }

                // Log upload to project history
                await fetch('/api/projects/log-upload', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({
                        projectId: project.id,
                        uploadRecord: {
                            platform: 'youtube',
                            videoId: videoId,
                            url: data.url,
                            status: privacy
                        }
                    })
                }).catch(err => console.error("Failed to log upload:", err));

                onUploadSuccess(data.url);
                alert(`Upload Successful!\nURL: ${data.url}`);
                onClose();
            } else {
                throw new Error(data.error || "Upload failed");
            }
        } catch (e: any) {
            alert("Upload Error: " + e.message);
        } finally {
            setLoading(false);
        }
    };

    return (
        <div className="fixed inset-0 z-[400] bg-black/80 backdrop-blur-sm flex items-center justify-center p-4 animate-in fade-in zoom-in-95 duration-200">
            <div className="bg-[#1a1a1a] w-full max-w-2xl rounded-2xl border border-white/10 shadow-2xl flex flex-col max-h-[90vh] overflow-hidden">

                {/* Header */}
                <div className="p-4 border-b border-white/10 flex justify-between items-center bg-black/20">
                    <h3 className="font-bold text-lg text-white flex items-center gap-2">
                        <Upload className="w-5 h-5 text-purple-400" /> Upload to SNS
                    </h3>
                    <button onClick={onClose} disabled={loading} className="p-1 hover:bg-white/10 rounded-full text-gray-400 hover:text-white"><X className="w-5 h-5" /></button>
                </div>

                <div className="flex-1 overflow-y-auto p-6 space-y-6">

                    {/* Platform Selector */}
                    <div className="flex gap-4">
                        <button
                            onClick={() => setPlatform('youtube')}
                            className={clsx("flex-1 p-4 rounded-xl border flex flex-col items-center gap-2 transition-all",
                                platform === 'youtube' ? "bg-red-600/10 border-red-600/50" : "bg-black/20 border-white/5 opacity-50 hover:opacity-100"
                            )}
                        >
                            <div className="w-10 h-10 bg-red-600 rounded-full flex items-center justify-center text-white"><Play className="w-5 h-5 fill-current" /></div>
                            <span className="font-bold text-sm">YouTube</span>
                        </button>
                        {/* Future Platforms */}
                        <button disabled className="flex-1 p-4 rounded-xl border border-white/5 bg-black/20 flex flex-col items-center gap-2 opacity-30 cursor-not-allowed">
                            <div className="w-10 h-10 bg-gradient-to-br from-pink-500 to-purple-600 rounded-full"></div>
                            <span className="font-bold text-sm">Instagram</span>
                        </button>
                    </div>

                    {/* Connection Check */}
                    {platform === 'youtube' && (
                        <div className={clsx("p-3 rounded-lg flex items-center justify-between text-sm", status?.connected ? "bg-green-500/10 text-green-300" : "bg-red-500/10 text-red-300")}>
                            <div className="flex items-center gap-2">
                                {status?.connected ? <CheckCircle className="w-4 h-4" /> : <X className="w-4 h-4" />}
                                {status?.connected ? `Connected as ${status.channelName}` : "Not Connected"}
                            </div>
                            {!status?.connected && (
                                <button onClick={() => window.open('/api/auth/youtube/login', '_blank', 'width=500,height=600')} className="underline hover:text-white">Connect Now</button>
                            )}
                        </div>
                    )}

                    {/* Metadata Inputs */}
                    <div className="space-y-4">
                        <div>
                            <label className="block text-xs font-bold text-gray-500 uppercase mb-1">Video Title</label>
                            <input
                                value={title}
                                onChange={e => setTitle(e.target.value)}
                                className="w-full bg-black/30 border border-white/10 rounded-lg p-3 text-white focus:border-purple-500 outline-none"
                            />
                        </div>

                        <div>
                            <label className="block text-xs font-bold text-gray-500 uppercase mb-1">Description</label>
                            <textarea
                                value={description}
                                onChange={e => setDescription(e.target.value)}
                                rows={5}
                                className="w-full bg-black/30 border border-white/10 rounded-lg p-3 text-white focus:border-purple-500 outline-none resize-none"
                            />
                        </div>

                        <div>
                            <label className="block text-xs font-bold text-gray-500 uppercase mb-1">Tags (comma separated)</label>
                            <input
                                value={tags}
                                onChange={e => setTags(e.target.value)}
                                placeholder="AI, Vlog, Tech..."
                                className="w-full bg-black/30 border border-white/10 rounded-lg p-3 text-white focus:border-purple-500 outline-none"
                            />
                        </div>

                        <div>
                            <label className="block text-xs font-bold text-gray-500 uppercase mb-2">Privacy</label>
                            <div className="flex bg-black/30 p-1 rounded-lg border border-white/10">
                                {(['private', 'unlisted', 'public'] as const).map(p => (
                                    <button
                                        key={p}
                                        onClick={() => setPrivacy(p)}
                                        className={clsx(
                                            "flex-1 py-2 rounded-md text-xs font-bold flex items-center justify-center gap-2 transition-all",
                                            privacy === p ? "bg-white/10 text-white shadow" : "text-gray-500 hover:text-gray-300"
                                        )}
                                    >
                                        {p === 'private' && <Lock className="w-3 h-3" />}
                                        {p === 'unlisted' && <EyeOff className="w-3 h-3" />}
                                        {p === 'public' && <Globe className="w-3 h-3" />}
                                        {p.charAt(0).toUpperCase() + p.slice(1)}
                                    </button>
                                ))}
                            </div>
                        </div>
                    </div>

                </div>

                {/* Footer */}
                <div className="p-4 border-t border-white/10 bg-black/20 flex justify-end gap-3">
                    <button onClick={onClose} disabled={loading} className="px-4 py-2 rounded-lg text-sm font-bold text-gray-400 hover:text-white hover:bg-white/5 transition-colors">Cancel</button>
                    <button
                        onClick={handleUpload}
                        disabled={loading || !status?.connected}
                        className="px-6 py-2 rounded-lg bg-red-600 hover:bg-red-500 disabled:bg-gray-700 disabled:text-gray-500 text-white text-sm font-bold shadow-lg shadow-red-900/20 transition-all flex items-center gap-2"
                    >
                        {loading ? <Loader2 className="w-4 h-4 animate-spin" /> : <Upload className="w-4 h-4" />}
                        {loading ? 'Uploading...' : 'Upload Video'}
                    </button>
                </div>

            </div>
        </div>
    );
}
